apiVersion: v1
name: wire-utility
description: A Helm chart for Wire utility debug pod
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - wire
  - utility
  - debug
maintainers:
  - name: Wire service delivery team