kube-prometheus-stack:
  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: letsencrypt-http01 # namespaced scope issuer. Copy the issuer from default namespace to a different namespace one where the chart is installed.
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Prometheus"
      ingressClassName: nginx
      hosts:
        - "prometheus.<domain_name>" #replace with your domain
      # The secretName is used to store the TLS certificate and key for the Prometheus ingress.
      path: /
      tls:
      - hosts:
        - prometheus.<domain_name> #replace with your domain
        secretName: <tls_secret_name> # replace with your preferred secret name (eg. prometheus-tls-cert), cert-manager will create this automatically
    service:
      type: ClusterIP

  # Both Grafana and Alertmanager is disabled in this configuration.
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  # This section is used to create a secret for basic authentication in the Prometheus ingress.
  # The secret contains a base64 encoded username and password.
  # NOTE: crete this secret using the following command:
  # htpasswd -nb admin <secure_password> | base64
  extraManifests:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: prometheus-basic-auth
        namespace: monitoring # replace with your namespace
      type: Opaque
      data:
        auth: <base64_encoded_username_password> # replace with your base64 encoded username and password
