apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-endpoint-manager
  namespace: default
  labels:
    app: postgres-endpoint-manager
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5

  jobTemplate:
    spec:
      # Keep completed jobs around for debugging
      ttlSecondsAfterFinished: 3600  # Keep pods for 1 hour after completion
      backoffLimit: 1
      activeDeadlineSeconds: 180

      template:
        spec:
          serviceAccountName: postgres-endpoint-manager
          restartPolicy: Never

          containers:
          - name: endpoint-manager
            image: quay.io/wire/wire-utility-tool:pg-manager-latest
            imagePullPolicy: Always

            # Optional: Override default node configuration via environment
            env:
            - name: TZ
              value: "UTC"
            - name: PGPASSWORD
              value: "securepassword"
            - name: PGUSER
              value: "repmgr"
            - name: PGDATABASE
              value: "repmgr"
            - name: PGCONNECT_TIMEOUT
              value: "5"
            - name: PG_NODES
              value: "{{ join "," (concat .Values.RWIPs .Values.ROIPs) }}"


            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "200m"

            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL