apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-endpoint-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres-endpoint-manager
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "patch"]
  resourceNames: ["{{ .Chart.Name }}-rw", "{{ .Chart.Name }}-ro"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-endpoint-manager
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: postgres-endpoint-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: postgres-endpoint-manager
  apiGroup: rbac.authorization.k8s.io
