{{- if and .Values.storageClassName .Values.storageSize .Values.volumeMountPath .Values.nodeName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-local-pv
spec:
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  local:
    path: {{ .Values.volumeMountPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodeName }}
{{- else }}
{{- fail "Error: All values (storageClassName, storageSize, volumeMountPath, nodeName) are required for creating PersistentVolume" }}
{{- end }}