{{- if (index .Values "kube-prometheus-stack" "prometheus" "ingress" "enabled") }}
{{- $prometheusAuth := .Values.auth | default dict }}
{{- $prometheusAuthUsername := $prometheusAuth.username | default "" }}
{{- $prometheusAuthPassword := $prometheusAuth.password | default "" }}
{{- if or (not $prometheusAuth)
          (not $prometheusAuthUsername)
          (not $prometheusAuthPassword) }}
{{- fail "\nError: Both 'username' and 'password' are required under 'auth' block.\nPlease ensure secrets.yaml file is loaded with -f flag and contains:\nauth:\n  username: <username>\n  password: <password>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd $prometheusAuthUsername $prometheusAuthPassword | b64enc }}
{{- end }}
