{{- if not .Values.prometheus.auth }}
{{- fail "Error: prometheus.auth value is required. Please ensure authsecret.yaml is loaded with -f flag." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ .Values.prometheus.auth | b64enc }}