{{- $prometheus := .Values.prometheus | default dict }}
{{- $prometheusAuth := $prometheus.auth | default "" }}
{{- if not $prometheusAuth }}
{{- fail "Error: prometheus.auth value is required. Please ensure authsecret.yaml is loaded with -f flag." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ $prometheusAuth | b64enc }}