{{- if (index .Values "kube-prometheus-stack" "prometheus" "ingress" "enabled") }}
  {{- $prometheus := .Values.prometheus | default dict }}
  {{- $prometheusAuth := $prometheus.auth | default dict }}
  {{- $username := $prometheusAuth.username | default "" }}
  {{- $password := $prometheusAuth.password | default "" }}
  {{- if or (eq $username "") (eq $password "") }}
    {{- fail "\nError: Both 'username' and 'password' are required under 'prometheus.auth'.\nPlease ensure you load secret values file with -f flag and contains:\n\nprometheus:\n  auth:\n    username: <username>\n    password: <password>\n" }}
  {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd $username $password | b64enc }}
{{- end }}
