{{- if and .Values.auth.username .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd .Values.auth.username .Values.auth.password | b64enc }}
{{- else }}
{{- fail "Error: Both auth.username and auth.password are required when ingress is enabled." }}
{{- end }}
